### ISSUE TITLE
infinite task running

### ISSUE THREAD

**Issue by Pozaza** [lazuee/poe.js#1]
when i try to ask model, the model not responding
![image](https://user-images.githubusercontent.com/71646021/236921710-55941533-ce2f-417d-9d52-36dbdd3f5058.png)

**Comment by lazuee** [comment]
> when i try to ask model, the model not responding ![image](https://user-images.githubusercontent.com/71646021/236921710-55941533-ce2f-417d-9d52-36dbdd3f5058.png)

what model you're using?

**Comment by Pozaza** [comment]
> > when i try to ask model, the model not responding ![image](https://user-images.githubusercontent.com/71646021/236921710-55941533-ce2f-417d-9d52-36dbdd3f5058.png)
> 
> what model you're using?

I've tried Claude-instant and Sage

**Comment by lazuee** [comment]
@Pozaza do you still get this error?

**Comment by Pozaza** [comment]
> @Pozaza do you still get this error?

Omg, it worked
