### ISSUE TITLE
No poe has been settled??

### ISSUE THREAD

**Issue by MiDo-kun** [lazuee/poe.js#2]
![Annotation 2023-06-29 122247](https://github.com/lazuee/poe.js/assets/72369026/c63e8cd2-2ad0-4e8c-ab7f-fd39d6cdae86)

Been trying multiple cookie value on it but it wont work. 
Also yesterday it works.

**Comment by lazuee** [comment]
@MiDo-kun If there are no Poe class sets on the map, it indicates that there is an issue with initializing the Poe.
Did you use the [example > multiple.cjs](https://github.com/lazuee/poe.js/blob/main/examples/multiple.cjs)? If you used it, you must have get error if the [token invalid](https://github.com/lazuee/poe.js/blob/main/examples/multiple.cjs#L16-L20).
Also, check if your poe token correct.

**Comment by lazuee** [comment]
If you are using the example given, check if you are getting you env variables. 
It should look like this.
```env
POE_TOKENS="poe_token1|poe_token2|poe_token3"
```

**Comment by lazuee** [comment]
If you are using the example given, check if you are getting your .env variables. 
It should look like this.
```env
POE_TOKENS="poe_token1|poe_token2|poe_token3"
```

**Comment by MiDo-kun** [comment]
Already checked but still no response. Dunno why.

**Comment by lazuee** [comment]
@MiDo-kun Looks like Poe changed variable name, payload to data in next_data. Anyways, Check new updates and install latest version **0.1.6**.
Also, check examples.

**Comment by MiDo-kun** [comment]
Will do thanks

**Comment by MiDo-kun** [comment]
![Annotation 2023-06-30 150714](https://github.com/lazuee/poe.js/assets/72369026/58dec160-eb2c-4343-9736-bdbf23f5f079)

Error encountered if the tokens are being enclosed with a single qoutation marks.

> If you are using the example given, check if you are getting your .env variables. It should look like this.
> 
> ```dotenv
> POE_TOKENS="poe_token1|poe_token2|poe_token3"
> ```
